# Funding platforms for this repository.
# Uncomment and fill in the ones you use, then delete the rest.
# See https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: # up to 4 GitHub Sponsors usernames, e.g. [user1, user2]
# patreon: # a single Patreon username
# open_collective: # a single Open Collective username
# ko_fi: # a single Ko-fi username
# liberapay: # a single Liberapay username
# buy_me_a_coffee: # a single Buy Me a Coffee username
# custom: # up to 4 custom URLs, e.g. ['https://example.com/donate']
